# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3.8" так как это - самая свежая версия на момент написания этого кода.

version: "3.8"

# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:

  # Понятное название сервиса помогает определить его роль.
  # Здесь мы, для именования соответствующего сервиса, используем ключевое слово 'node_app'.

  node_app:
 
    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    # Здесь 'node_app/' соответствует пути к папке,
    # в которой содержится соответствующий Dockerfile.

    build: node_app/

    # Вспомните о том, что в качестве порта в 'node_app/server.js' указан порт 8080.
    # Если мы хотим обратиться к серверу с нашего компьютера (находясь за пределами контейнера),
    # мы должны организовать перенаправление этого порта на порт компьютера.
    # Сделать это нам поможет ключевое слово 'ports'.
    # При его использовании применяется следующая конструкция: [порт компьютера]:[порт контейнера]
    # В нашем случае нужно использовать порт компьютера 8080 и организовать его связь с портом
    # 8080 контейнера (так как именно на этот порт сервер ожидает поступления запросов).

    ports:
      - 8080:8080
