version: "3.8"

services:

  myapp:
 
    build: myapp/

    image: myapp:v1

    container_name: app

    networks:
      - myapp

  nginx:

    image: nginx:stable-alpine

    container_name: nginx_proxy

    ports:
      - "8081:8081"

    volumes: 
      - ./myapp/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - myapp
    links:
      - myapp

networks:
  myapp: 
