version: "3.8"

services:

  node_app:
 
    build: node_app/

    image: myapp:v1

    container_name: myapp

    networks:
      - myapp

  nginx:

    image: nginx:stable-alpine

    container_name: nginx_proxy

    ports:
      - "8081:8081"

    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - myapp

networks:
  myapp: 
