FROM node:15-alpine

# создание рабочей директории приложения
WORKDIR /usr/src/app

# установка зависимостей
# символ астериск ("*") используется для того чтобы по возможности 
# скопировать оба файла: package.json и package-lock.json
COPY package*.json ./

RUN npm install
# Если вы создаете сборку для продакшн
# RUN npm ci --only=production

# копируем исходный код в образ
COPY server.js ./

EXPOSE 8080
CMD [ "node", "server.js" ]
